# Generated by Django 4.2.5 on 2023-10-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_counted_views_post_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
